name: device_frame
description: Mockups for common devices.
version: 0.4.0
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_svg: 0.19.3
  path_drawing:  ^0.4.1+1
  freezed_annotation: ^0.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  freezed: ^0.14.0+1
  pedantic: ^1.9.0
  xml: ^4.2.0