name: device_preview
version: 0.7.1
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.12.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.5
  path_provider: ^1.5.0
  device_frame:
    path: ../device_frame
  font_awesome_flutter: ^9.0.0
  http: ^0.12.0+2
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.0
  shared_preferences: 0.5.12
  pedantic: ^1.10.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^1.10.3
  freezed: ^0.14.1
  json_serializable: ^4.0.2
#  analyzer: ^1.0.0
